[server]
# If false, will attempt to open a browser window on start.
headless = true

[browser]

# Don't send usage statistics
gatherUsageStats = false

[theme]

# Primary accent for interactive elements
primaryColor = '#ae1717'

# Background color for the main content area
backgroundColor = '#2b2a29'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#7c787f'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"